### ISSUE TITLE
Exercise 6 Task1 - Library mismatch for AutoML

### ISSUE THREAD

**Issue by euangms** [microsoft/MCW-Azure-Synapse-Analytics-end-to-end-solution#12]
We have a customer report that this fails due to an error in the dependencies on the packages, was anything done for the lab to get the right versions of the packages?

OptionalDependencyMissingException : OptionalDependencyMissingException: Message: Incompatible/Missing packages found: 
azureml-train-automl-runtime requires numpy<=1.16.2,>=1.16.0 but has numpy 1.18.5.;
azureml-train-automl-runtime requires onnxruntime==1.0.0 but has onnxruntime 0.4.0.;
azureml-defaults requires werkzeug==0.16.1 but has Werkzeug 0.16.0.
;azureml-automl-runtime requires nimbusml>=1.7.1 but has nimbusml 1.5.0.;
azureml-automl-runtime requires numpy<=1.16.2,>=1.16.0 but has numpy 1.18.5.;
azureml-automl-runtime requires onnxruntime==1.0.0 but has onnxruntime 0.4.0.;
azureml-core requires ruamel.yaml>0.16.7 but has ruamel.yaml 0.15.89.

**Comment by codingbandit** [comment]
We have been made aware that the Spark Pools in Synapse have been updated to use a newer versions of certain libraries than what is supported in the azureml-sdk. This has been reported to the product team.

**Comment by euangms** [comment]
Thanks do you know how it was reported? I work on the Spark engineering team and we found this out accidentally.

**Comment by euangms** [comment]
@codingbandit  we had the AutoML team debug this and you need to add a requirements.txt to the Spark pool with the following entries, this will resolve the version conflict;

onnxruntime==1.0.0 
werkzeug==0.16.1 
nimbusml==1.7.1 
ruamel.yaml==0.16.9
azureml-train-automl-runtime==1.6.0
scikit-learn==0.20.3
numpy==1.16.2
pandas==0.23.4

**Comment by codingbandit** [comment]
@euangms - thank you! I will look at incorporating those changes and testing. An answer to your question, the feedback was provided from an introspective after some training.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #13
