### ISSUE TITLE
Excercise 6 - Task 2 Registering the models with Azure Synapse Analytics

### ISSUE THREAD

**Issue by muarif2000** [microsoft/MCW-Azure-Synapse-Analytics-end-to-end-solution#14]
- Step 1: I couldn't locate https://github.com/microsoft/MCW-Azure-Synapse-Analytics-end-to-end-solution/raw/master/Hands-on lab/artifacts/convert-to-hex.ps1
I am not sure of instructions, Am i supposed to run the script? If yes How? I am assuming we are supposed to move to next step.

- So when i run Step 4. I get below error instead of showing me the model
"Failed to execute query. Error: HdfsBridge::recordReaderFillBuffer - Unexpected error encountered filling record reader buffer: MalformedInputException: Input length = 1
Total execution time: 00:00:01.090"

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #15
