### ISSUE TITLE
Exercise 2: Create and populate the supporting tables in the SQL Pool - Task 1: Create the sale table

### ISSUE THREAD

**Issue by magaudef** [microsoft/MCW-Azure-Synapse-Analytics-end-to-end-solution#17]
There is no data in the colum 'Transaction ID', so the pipeline is not working as we create the table with NOT NULL for this field.
Is it normal ? 
To be able to load the data I had to create the table with NULL for TransactionID

**Comment by codingbandit** [comment]
Hi @magaudef - please ensure that the mappings were setup properly (Exercise 2 - Task 2 - Step 19). I've verified and the Transaction ID is available in all parquet files (you can also confirm this through your environment by doing Exercise 3). It looks to me like the TransactionID column may have been inadvertently deleted when doing the exercise.
