### ISSUE TITLE
VS Code issue

### ISSUE THREAD

**Issue by Pedro-Martinez** [microsoft/MCW-Azure-Synapse-Analytics-end-to-end-solution#6]
Not really familiar with Visual Studio Code. I got a lot of errors while executing Task #5 and couldn't start the workshop. I suggest adding extra details to these steps with screen shots.

**Comment by Pedro-Martinez** [comment]
Creating Spark notebooks...
Creating notebook ASAMCW - Exercise 6 - Machine Learning from .\notebooks\ASAMCW - Exercise 6 - Machine Learning.ipynb
Create-SparkNotebook : The term 'Create-SparkNotebook' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:225 char:19
+         $result = Create-SparkNotebook -TemplatesPath $templatesPath  ...
+                   ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Create-SparkNotebook:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Wait-ForOperation : The term 'Wait-ForOperation' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:227 char:19
+         $result = Wait-ForOperation -WorkspaceName $workspaceName -Op ...
+                   ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Wait-ForOperation:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by codingbandit** [comment]
@Pedro-Martinez - please ensure that you have navigated to the automation folder in the terminal window when running the PowerShell scripts.  (step 4)

**Comment by liqsword** [comment]
Suggest to add "verify" steps by end of the "Before Lab Steps", so we can ensure the environment is ready for the HOL.

**Comment by Pedro-Martinez** [comment]
I confirm I navigated to the automation folder as mentioned in the step 4

**Comment by Pedro-Martinez** [comment]
PS C:\LabFiles\MCW\Hands-on-lab\environment-setup\automation\environment-automation> cd ..

PS C:\LabFiles\MCW\Hands-on-lab\environment-setup\automation> Remove-Module "environment-automation"
Import-Module ".\environment-automation"

Uninstall-AzureRm

Install-Module -Name Az -AllowClobber
Install-Module -Name Az.Storage -AllowClobber
Install-Module -Name Az.Resources -AllowClobber
Install-Module -Name Az.KeyVault -AllowClobber

**Comment by Pedro-Martinez** [comment]
Set-AzKeyVaultAccessPolicy : Cannot validate argument on parameter 'ResourceGroupName'. The argument is null or empty. Provide an argument that is not null or empty, 
and then try the command again.
At line:75 char:47
+ ... -AzKeyVaultAccessPolicy -ResourceGroupName $resourceGroupName -VaultN ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzKeyVaultAccessPolicy], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy

Get-Workspace : The term 'Get-Workspace' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:77 char:7
+ $ws = Get-Workspace $SubscriptionId $ResourceGroupName $WorkspaceName ...
+       ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-Workspace:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Set-AzKeyVaultAccessPolicy : Cannot validate argument on parameter 'ResourceGroupName'. The argument is null or empty. Provide an argument that is not null or empty, 
and then try the command again.
At line:79 char:47
+ ... -AzKeyVaultAccessPolicy -ResourceGroupName $resourceGroupName -VaultN ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzKeyVaultAccessPolicy], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy

Create SQL-USER-ASA Key Vault Secret
ConvertTo-SecureString : Cannot bind argument to parameter 'String' because it is null.
At line:82 char:39
+ $secretValue = ConvertTo-SecureString $sqlPassword -AsPlainText -Forc ...
+                                       ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertTo-SecureString], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertToSecureStringCommand

Set-AzKeyVaultSecret : Cannot bind argument to parameter 'SecretValue' because it is null.
At line:83 char:103
+ ... yVaultName -Name $keyVaultSQLUserSecretName -SecretValue $secretValue
+                                                              ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzKeyVaultSecret], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultSecret

Create KeyVault linked service asakeyvault
Create-KeyVaultLinkedService : The term 'Create-KeyVaultLinkedService' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:87 char:11
+ $result = Create-KeyVaultLinkedService -TemplatesPath $templatesPath  ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Create-KeyVaultLinkedService:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Wait-ForOperation : The term 'Wait-ForOperation' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:88 char:1
+ Wait-ForOperation -WorkspaceName $workspaceName -OperationId $result. ...
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Wait-ForOperation:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Create Integration Runtime AzureIntegrationRuntime01
Create-IntegrationRuntime : The term 'Create-IntegrationRuntime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:92 char:11
+ $result = Create-IntegrationRuntime -TemplatesPath $templatesPath -Su ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Create-IntegrationRuntime:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Wait-ForOperation : The term 'Wait-ForOperation' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:93 char:1
+ Wait-ForOperation -WorkspaceName $workspaceName -OperationId $result. ...
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Wait-ForOperation:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Pedro-Martinez** [comment]
Export-ModuleMember -Function Get-Workspace
Export-ModuleMember : The Export-ModuleMember cmdlet can only be called from inside a module.
At line:1470 char:1
+ Export-ModuleMember -Function List-StorageAccountKeys
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Export-ModuleMember], InvalidOperationException
    + FullyQualifiedErrorId : Modules_CanOnlyExecuteExportModuleMemberInsideAModule,Microsoft.PowerShell.Commands.ExportModuleMemberCommand
 
Export-ModuleMember : The Export-ModuleMember cmdlet can only be called from inside a module.
At line:1471 char:1
+ Export-ModuleMember -Function List-CosmosDBKeys
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Export-ModuleMember], InvalidOperationException
    + FullyQualifiedErrorId : Modules_CanOnlyExecuteExportModuleMemberInsideAModule,Microsoft.PowerShell.Commands.ExportModuleMemberCommand

Export-ModuleMember : The Export-ModuleMember cmdlet can only be called from inside a module.
At line:1472 char:1
+ Export-ModuleMember -Function Create-KeyVaultLinkedService
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Export-ModuleMember], InvalidOperationException
    + FullyQualifiedErrorId : Modules_CanOnlyExecuteExportModuleMemberInsideAModule,Microsoft.PowerShell.Commands.ExportModuleMemberCommand

**Comment by codingbandit** [comment]
@Pedro-Martinez - there is a pending PR to move the execution of the PowerShell scripts to the cloud shell - mitigating any issues that arise with differing local environment setup.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete - PR merged.
